trigger:
- main

pool: infraaagent
stages:
  - stage: Infrastructure_Init
    displayName: Infrastructure create
    jobs:
      - job: TerraformInstaller 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
      - job: init
        steps:

        - task: SonarQubePrepare@8
          inputs:
            SonarQube: 'sonarservices'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'shashipipeline_infrapretiesteraform_4ae83a96-643b-4298-9c0b-c6ce1212ae63'
            cliSources: '.'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)\infrasetting\environments\dev'
            backendServiceArm: 'infraservices'
            backendAzureRmResourceGroupName: 'product-rg'
            backendAzureRmStorageAccountName: 'productstgs4'
            backendAzureRmContainerName: 'pipelinecontainer'
            backendAzureRmKey: 'pipeline.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)\infrasetting\environments\dev'
  - stage: Deployment_Verification
    displayName: Deployment Verification
    jobs:
      - job: tfsec
        steps:
        - task: tfsec@1
          continueOnError: true
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)\infrasetting\environments\dev'
      - job: tflint
        steps:
        - task: PowerShell@2
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: |
              tflint
              tflint --init
              tflint --recursive
              errorActionPreference: 'continue'
            workingDirectory: '$(System.DefaultWorkingDirectory)\infrasetting\environments\dev'
  - stage: Infra_Planning
    displayName: Infra Planning
    jobs:
      - job: plan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)\infrasetting\environments\dev'
            backendServiceArm: 'infraservices'
            backendAzureRmResourceGroupName: 'product-rg'
            backendAzureRmStorageAccountName: 'productstgs4'
            backendAzureRmContainerName: 'pipelinecontainer'
            backendAzureRmKey: 'pipeline.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)\infrasetting\environments\dev'
            environmentServiceNameAzureRM: 'infraservices'
  - stage: Infrastructure_Deployment
    displayName: Infrastructure Deployment
    jobs:
      - job: apply
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)\infrasetting\environments\dev'
            backendServiceArm: 'infraservices'
            backendAzureRmResourceGroupName: 'product-rg'
            backendAzureRmStorageAccountName: 'productstgs4'
            backendAzureRmContainerName: 'pipelinecontainer'
            backendAzureRmKey: 'pipeline.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)\infrasetting\environments\dev'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: 'infraservices'
        - task: SonarQubeAnalyze@8
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'

        - task: SonarQubePublish@8
          inputs:
            pollingTimeoutSec: '300'



