trigger:
- main

pool: infraaagent

steps:
- task: PowerShell@2
  displayName: Az login
  inputs:
    targetType: 'inline'
    script: |
      az login --service-principal `
        --username "$(ARM_CLIENT_ID)" `
        --password "$(ARM_CLIENT_SECRET)" `
        --tenant "$(ARM_TENANT_ID)"

- task: PowerShell@2
  displayName: Terraform init, fmt, validate
  inputs:
    targetType: 'inline'
    script: |
      cd environments/dev
      terraform init
      terraform fmt
      terraform validate

- task: PowerShell@2
  displayName: Terraform plan
  inputs:
    targetType: 'inline'
    script: |
      terraform plan
