# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: infraaagent

steps:
- task: PowerShell@2
  displayName: Az login
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      az login --service-principal`
         --username "$(ARM_CLIENT_ID)"` 
         --password "$(ARM_CLIENT_SECRET)"` 
         --tenant "$(ARM_TENANT_ID)"
- task: PowerShell@2
  displayName: Terraform init,Fmt
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      cd environments/dev
      terraform init
      terraform fmt
      terraform validate
- task: PowerShell@2
  displayName: Terraform plan
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      terraform plan